const facultydata = [
    {
        facultyName:"Faculty of Education",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course10:"Education and Islamic Studies",
        course11:"Education and English Language"
    },
    {
        facultyName:"Faculty of Engineering",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    {
        facultyName:"Faculty of Art",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    {
        facultyName:"Faculty of Science",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    {
        facultyName:"Faculty of Education",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    
    {
        facultyName:"Faculty of Education",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    
    {
        facultyName:"Faculty of Education",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
    
    {
        facultyName:"Faculty of Education",
        course1:"Adult Education",
        course2:"Arts & Social Science Education",
        course3:"Education Administration",
        course4:"Educational Foundations",
        course5:"Human Kinetics and Health Education",
        course6:"Science Tech, Education",
        course7:"Business Education",
        course8:"Home Economics and Education",
        course9:"Education and Christians Religious Studies",
        course9:"Education and Islamic Studies",
        course10:"Education and English Language"
    },
]
export default facultydata;